### ISSUE TITLE
Usage of deprecated method relativeRoute

### ISSUE THREAD

**Issue by kuehnelth** [Tobi2K/ktlint-gitlab-reporter#1]
I tried using this module with a ktlint 0.47 snapshot and it crashes because `relativeRoute` was removed.
In 0.46 it's marked as deprecated.
https://github.com/pinterest/ktlint/blob/0.46.1/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/internal/CurrentBaseline.kt#L127

**Comment by Tobi2K** [comment]
Hello and thank you for your issue!

I published a fix [here](https://github.com/Tobi2K/ktlint-gitlab-reporter/tree/1-usage-of-deprecated-method-relativeroute). The new .jar should work now and I also added JSON escaping. I will be merging the branch and closing this issue later today.

**Comment by kuehnelth** [comment]
Awesome. Thanks for the quick fix.
