### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by piotrp** [Tobi2K/ktlint-gitlab-reporter#4]
If you publish this reporter then usage would be much simpler, and JAR downloading could be easily automated with build tools. Various ktlint integrations for eg. for Gradle or Maven make it easy to do for published reporters.

**Comment by Tobi2K** [comment]
Sure, that makes sense. I will look into it.

**Comment by Tobi2K** [comment]
The reporter is now published on Maven Central. The package is available at `io.github.tobi2k:ktlint-gitlab-reporter`.
See also the [Maven Central/Sonatype page](https://central.sonatype.com/artifact/io.github.tobi2k/ktlint-gitlab-reporter/1.0.0/overview)
