### ISSUE TITLE
Generated report does not adhere to spec

### ISSUE THREAD

**Issue by zwolsman** [Tobi2K/ktlint-gitlab-reporter#6]
After running the gitlab reporter there are not results shown; reason being the report does not adhere to the spec (https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types).

Only part of the spec is filled in

**Example result**
```json
[
    {
        "description": "x:183 - Unexpected indentation (20) (should be 16) (Rule: standard:indent)",
        "severity": "major",
        "location": {
            "path": "x",
            "lines": {
                "begin": 183
            }
        }
    }
]
```

**Missing fields**
type, check_name and categories.

**Proposal**
`type` should always be `issue`
`categories` can always be `Style`.
`check_name` could be the rule name that was violated (e.g. `standard:indent`)

**Comment by Tobi2K** [comment]
Hi there,
The `check_name` field seems to be a (more or less) new requirement. `type` and `categories` do not need to be set for GitLab CLI (see [GitLab CLI Custom Tools](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool)). I will also add those, as it still works if they _are_ present. Thanks for the heads up.

**Comment by zwolsman** [comment]
Also `fingerprint` when you look at the docs

**Comment by Tobi2K** [comment]
Yes, that is added in the pull request as well.

**Comment by zwolsman** [comment]
Thank you for the quick reply! Let's see if it works now 👍🏽

**Comment by Tobi2K** [comment]
No problem, I'm happy to help. Please let me know if it works once you've tried it.
